title: Casoon UI Library
description: Eine moderne, responsive UI-Bibliothek für Webanwendungen
baseurl: "/casoon-ui-lib"
url: "https://casoon.github.io"

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  foundation:
    output: true
  components:
    output: true
  examples:
    output: true

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "foundation"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "components"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "examples"
    values:
      layout: "default" 

include:
  - css/_reset.css
  - css/_layout.css
  - css/_typography.css
  - css/_utilities.css
  - css/_components.css
  - css/_forms.css
  - css/_smooth-scroll.css
  - css/_tokens.css