title: Casoon UI Library
description: Eine modulare CSS-Bibliothek für moderne Webanwendungen
baseurl: "/casoon-ui-lib"
url: "https://casoon.github.io"

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  core:
    output: true
  components:
    output: true
  examples:
    output: true

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: default

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore 
