name: Copy CSS to /docs

on:
  push:
    branches:
      - master  # passe ggf. deinen Branchnamen an
    paths:
      - 'base/**'
      - 'themes/**'
      - '*.css'
      - '*.md'
      - '!docs/**' # keine Reaktion auf Änderungen innerhalb von /docs
  workflow_dispatch:  # 👈 Damit kannst du die Action manuell starten

permissions:
  contents: write  # 🔓 Erlaubt Push zurück ins Repo

jobs:
  copy-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 📂 Copy CSS to /docs/css
        run: |
          mkdir -p docs/css
          cp -r *.css docs/css/

      - name: 📂 Copy Themes to /docs/css/themes
        run: |
          mkdir -p docs/css/themes
          cp -r themes/*.css docs/css/themes/

      - name: 📂 Copy Base to /docs/css/core
        run: |
          mkdir -p docs/css/core
          cp -r core/*.css docs/css/core/

      - name: 📂 Copy Components to /docs/css/core/components
        run: |
          mkdir -p docs/css/core/components
          cp -r core/components/*.css docs/css/core/components/



      - name: ✅ Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add docs/css
          git commit -m "🧹 Auto-copy CSS files to /docs/css" || echo "No changes to commit"
          git push
